version: "3.8"
services:
  monolith-gui:
    container_name: monolith-gui
    image: esotericlabs/monolith-gui:latest
    restart: unless-stopped
    network_mode: host
    user: "1000:1000"
    volumes:
      - /opt/monolith-gui/data:/data
    environment:
      - MONOLITH_ENV=production
